### PR TITLE
** MAJOR SECURITY FLAW** CWD is not limited!

### PR DESCRIPTION
**Pull request by RyanCopley**
With this FTP server, you can traverse the entire filesystem. This patch fixes that.

### CODE REVIEW

**Comment by RyanCopley** [comment]
I'm not doing anything custom. I followed the directions in the readme.md and using NodeJS 0.12.x I can easily escape the CWD. I am doing *nothing* special here-- I just hit command+up in Cyberduck. This flaw exists in two places in the code, I just committed the other spot. 

Try it. You can escape the CWD.

**Comment by addrummond** [comment]
If I run `test.js` and connect with Cyberduck, I can't escape out of the root dir using command+up.

**Comment by RyanCopley** [comment]
getInitialCwd: Gets the initial working directory for the user. Called after user is authenticated.

getRoot: Gets the root directory for the user relative to the CWD. Called after getInitialCwd. The user is not able to escape this directory.

That has to be the most confusing way (and most confusing example) to explain that, if what you said is what you meant vs what is in the README.md file...

**Comment by addrummond** [comment]
Yes, the README is screwed up. (In my defense, I don't think I personally wrote the inaccurate parts, but anyway, it needs to be changed.) The function of the two options is actually quite simple. `getRoot` just returns the directory within the actual filesystem out of which the FTP server can never escape. `getCwd` just sets the initial working dir for the user, relative to the path specified by `getRoot`. The user is free to escape the initial CWD.

Anyway, given the bad docs and bad example code, it's entirely understandable that you raised a security concern. However, I think the flaw here is just with the documentation, not the code.

**Comment by RyanCopley** [comment]
While I have you're attention, the `host` variable should probably be clarified (if it is, my mistake), that it is for what the server tells the client to connect to that address for passive mode. I spent a lot of time confused why setting the host to `0.0.0.0` would fail to transfer files...

**Comment by RyanCopley** [comment]
and yes... switching around my getInitialCWD and getRoot implementations and now I cannot escape my sandbox :+1:

**Comment by addrummond** [comment]
Thanks, I will try to get around to updating the Readme in the next few days. (Feel free to submit a pull request for that if you have the time and inclination.)

I'm going to close this issue now since there is not strictly speaking any security issue here, but thanks again for pointing out these problems in the docs.

**Comment by sstur** [comment]
Thanks @RyanCopley for bringing this up. I agree it is confustion and should be better explained (maybe some safety net put in place to prevent people from swapping them). Neither myself nor @addrummond wrote this part of the Readme, but I'll fix it. Thanks!

**Comment by RyanCopley** [comment]
Still doesn't seem to be updated...

**Pull request closed without merging**
