### PR TITLE
Fix retr when file not found

### PR DESCRIPTION
**Pull request by phillipgreenii**
This is a fix for #55; it ensure 550 is sent before 150 when a file is not found; additional tests were added for RETR.

### CODE REVIEW

**Comment by sstur** [comment]
This mostly looks good to me. There's a few style issues like spaces after function keyword but it seems like a good fix. It looks like you're working on the test failure. Also, can you rebase your branch rather than merge so we don't have the commit "Merge branch 'master'..."

**Comment by phillipgreenii** [comment]
What is the best way to rebase now that I have already merged?  Should I close this pull request and create a new one with a new branch?

**Comment by sstur** [comment]
You could do that. Or you can git rewrite the history on your branch and do a `git push --force` I think. Whatever works for ya

**Comment by sstur** [comment]
See: https://github.com/sstur/nodeftpd/commits/fixRETRwhenFileNotFound

**Comment by phillipgreenii** [comment]
Is there anything more you need for this PR?

**Pull request merged**
