### PR TITLE
Simplify checking if finished logic

### PR DESCRIPTION
**Pull request by joshbuddy**
I was running into an issue where it would never return from here, and simplifying this logic fixed it for me. Sorry I don't have a better test for it, but hopefully you agree that this is a simpler way to achieve what you're after.

### CODE REVIEW

**Comment by sstur** [comment]
Nice fix. Thanks!

**Comment by joshbuddy** [comment]
Sorry .. one more fix to the logic. Fixed up test to reflect change (and expose bug)

**Comment by sstur** [comment]
Much better. Thanks for updating the tests.

**Comment by addrummond** [comment]
Thanks joshbuddy. What do you guys think about just using async.forEachLimit here? I think originally I wanted to avoid the dependency, but it's always hard to be confident that the logic is correct doing it by hand.

**Comment by joshbuddy** [comment]
Honestly, I would have just modified the original list by popping off the next entry, but I wanted to retain the spirit of the code and not modify the original list (though it looks harmless to do so in this case). I'm okay with either solution, but generally prefer not bringing in deps unless I absolutely need to.

**Comment by joshbuddy** [comment]
Here is the simpler implementation: https://github.com/sstur/nodeftpd/pull/71

**Comment by addrummond** [comment]
Nice. I'm totally fine with either version. I'd still vote for using a lib such as async,  just because it makes the intent immediately clear. But if Simon wants to go ahead and merge I have no objection.

**Comment by mk-pmb** [comment]
I consider concise expression of intent as more important than avoiding dependencies. If dependencies are in the spirit of focussing on one thing and doing that right, they're much better than reinventing the wheel, and they promote modularity. If some maintainance programmer or a runtime know of a better implementation (most times: more performant), they can more easily swap it in at a module boundary, and (hopefully) can trust that nodeftpd only relies on the documented features, not on all the emergent details. (Questions like "Will it matter where the `this` context is carried?")

Especially for flow control, in a debug scenario, that "better implementation" can be one with long stack traces, user-controled scheduling etc., that may be readily available on npm for standard libs, but cumbersome for re-invented wheels.

**Comment by sstur** [comment]
I'll merge this one and https://github.com/sstur/nodeftpd/pull/71.

I tend to agree with @mk-pmb and @addrummond with regards to dependencies. I'm OK will pulling in a well tested library to do something useful.

**Pull request merged**
