### PR TITLE
Add a test for file paths with unusual characters in them.

### PR DESCRIPTION
**Pull request by mk-pmb**
In case I included characters that are invalid by RFC or similar rulesets, let's instead make `ftpd` reply with an error message, and add a note in the source which rule would be violated by that character.

### CODE REVIEW

**Comment by sstur** [comment]
This looks good. Couple small code style issues, but I will go ahead and merge this and fix the code style when I get ESLint added. Thanks!

**Comment by sstur** [comment]
There is some console noise when I run the tests:
    sstur@local:ftpd$ npm test

    > ftpd@0.2.12 test /Users/Me/projects/ftpd
    > mocha test/*.js

    (node) child_process: options.customFds option is deprecated. Use options.stdio instead.

      ․․․ERROR: CWD usr/local: Error: ENOENT: no such file or directory, stat '/Users/Me/projects/ftpd/fixture/jose/usr/local/usr/local'
    ․․․․․․․getRoot signaled error [Error: intentional failure]
    Client connection closed
    ․․․․getInitialCwd signaled error [Error: intentional failure]
    Client connection closed
    ․․․․․․․ERROR: MKD /testdir: Error: EEXIST: file already exists, mkdir '/Users/Me/projects/ftpd/fixture/jose/testdir'
    ․․ERROR: RMD /testdir: Error: ENOENT: no such file or directory, rmdir '/Users/Me/projects/ftpd/fixture/jose/testdir'
    ․․․․․․․․․․․․․․․․․․․ERROR: CWD tricky_paths/b\\s\l, """"q'u""o""te''; pi|p|e & ^up^: Error: ENOENT: no such file or directory, stat '/Users/Me/projects/ftpd/fixture/jose/tricky_paths/b\\s\l, """"q'u""o""te''; pi|p|e & ^up^'
    ․ERROR: CWD tricky_paths/b\\s\l, """"q'u""o""te''; pi|p|e & ^up^: Error: ENOENT: no such file or directory, stat '/Users/Me/projects/ftpd/fixture/jose/tricky_paths/b\\s\l, """"q'u""o""te''; pi|p|e & ^up^'
    ․․․․․․․․․․․․․․․․․․․․

      63 passing (283ms)

Maybe you can look into cleaning this up and submit a fix? Please pull the latest code first since I fixed code style issues and added ESLint to enforce these styles going forward. Thanks!

**Comment by mk-pmb** [comment]
Preparing a new PR:
 * [x] <del>use camel case</del>
 * [x] variable declaration in their own statements (in the new test and retr test)
 * [x] fixed `options.customFds` warning by upgrading `mocha` to v^2.3.4
 * [x] clean up error log in tests
 * [ ] convert to new eslint-enforced style

**Comment by sstur** [comment]
> convince @sstur that Crockford style is superior ;-)

Hehe, Crockford certainly thinks so! Actually besides the fact that he likes to use ruby_style_vars, I think our styles are mostly similar, no?

**Comment by mk-pmb** [comment]
Current eslint config forbids the trailing comma, but it is meant to hint at coder's possibility to add more expected messages. Also, with current eslint settings, this line would have to be changed (comma added again) if another message was to be added, causing needless diff flickering and making automatic merges more complicated for git.
```js
            server.suppressExpecteErrMsgs.add([
              /^ERROR: CWD [\S\s]+: Error: ENOENT, stat 'fixture:/,
            ]);
```
Should I adapt the code or the eslint settings?

**Comment by mk-pmb** [comment]
Yup, seems mostly compatible. I even got the "tricky paths" test to jslint again, with additional settings to allow multiple var declarations and confusing whitespace. ;-) The bracket style inflates a lot of statements like `if (…) { return; }` but that's a matter of taste.

**Comment by sstur** [comment]
Actually, I agree with you about the `if (...) return;` is nicer as a one liner without braces. What I was trying to avoid with that lint rule is:

    if (...)
      doSomething();
    else
      doSomethingElse();

which is ugly (and arguably dangerous) without braces. If we can allow brace-less one-liners without allowing multi-line/multi-clause then I'm sold.

The trailing comma is a longer discussion, but I agree to some extent about "needless diff flickering". A lot of my style is influenced from writing code at FB where we realized this problem (specifically the blame of a line) and even created a lint rule to always enforce trailing commas. That lead to enforcing trailing commas on multi-line Object literals and then eventually function calls and then function definitions:

    var thing = {
      foo: 1,
      bar: 2,
    }

    return doSomething(
      123,
      'xyz',
    );

    function doSomething(
      foo,
      bar,
    ) { ... }

Because of how strongly the JS engineers felt about this trailing comma, I think we actually got the ECMAScript committee to accept a proposal to allow trailing commas which will likely land in ES7.

Anyway, the point is, if you start down the road of trailing commas, that's where it leads...

I like consistency, so if we decide to go down the road of trailing commas, we should enforce it across the codebase. For now, I'm happy if you add a /* eslint-disable comma */ directive at the top of test files and we can fix it later.

**Comment by sstur** [comment]
Oh, about the `if ((typeof client) === 'string') {` issue, can you explain?

**Comment by mk-pmb** [comment]
> I think we actually got the ECMAScript committee to accept a proposal to allow trailing commas which will likely land in ES7.

Usually I'm for adapting the tool (here: git) to the problem (a lot of (human) languages' tendency to omit trailing separators on lists). However, since I don't think I can (help to) solve either of both, I'd readily accept to blot the language.

About yoda:
```js
isNum = (typeof x === 'number');    // confusing
isNum = ('number' === typeof x);    // yoda: Expected literal to be on the right side of ===
```
I consider the first variant confusing about the greediness of `typeof`. I even thought jslint had told me to use the second variant, but current versions don't complain. Still, readers will have to stop and remember precedence details to decide whether `isNum` will be a Boolean or the string `'boolean'`, and whether that could be source of the but they're hunting.

**Comment by sstur** [comment]
Oh, I get it! I never heard of it called that, but [from my trivial understanding of star wars references] that yoda term actually makes sense!

Anyway, I've seen it written `typeof x === 'number'` for so many years I never thought of it as confusing. On the contrary, I've occasionally seen repos do it the reverse way and thought "hmm, I wonder why they put the string first. That's weird." I guess that's why style is so subjective: what's confusing for one person makes perfect sense to another, largely depending on background. It's probably a fallacy to look at any patterns as a seasoned coder and think "this would be evident/confusing to a newcomer reading this code".

We can probably go back and forward about this style stuff indefinitely, but with regards to the Crockford practice of manually hoisting `var` declarations to the top of the scope: I understand your point about how it self-documents the function in a way, however I feel it strongly that it puts unnecessary distance between the description of a thing and it's implementation and I feel it adds boilerplate (oh, did I add this one to the list yet? or remove this other one after deleting the statement?). I suspect those are the reasons why it is not commonly done this way in the JS community. I think of that kind of manual declaring-elsewhere-before-use kind of old school, like writing c++ header files. But again, it's all subjective.

Anyway, I'll add a contributing doc to this repo to clear it all up for future contributors..

**Comment by mk-pmb** [comment]
When var declarations get too far away from where they're used, it's usually a code smell that their function might span too many lines. In my patch to `test/common.js` that was a pretty clear case, and if I were to define the project's style, a lot of anon functions would have to go somewhere else, get names and be referenced by them. Wrapping some parts into an [IIFE](https://en.wikipedia.org/wiki/Immediately-invoked_function_expression) can help, too, and offers another opportunity to _name more code_℠.

> Anyway, I'll add a contributing doc to this repo to clear it all up for future contributors..

:+1:

**Comment by sstur** [comment]
@mk-pmb I have updated eslint to match your style with trailing commas on multi-line array/object literals.

On another note, I've put up a diff to clean up the logging. Would you mind reviewing my diff to make sure I haven't missed anything: https://github.com/sstur/nodeftpd/commit/79d3996a161e2b5b62e7eaa8f155fc207b568404

**Comment by mk-pmb** [comment]
[x] Done.

**Pull request merged**
